registry:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - ./data:/data

jenkinsdata:
  build: jenkins-data

jenkinsmaster:
  build: jenkins-master
  volumes_from:
    - jenkinsdata
  ports:
    - "127.0.0.1:50000:50000"

nginx:
  image: "nginx:1.9"
  ports:
    - "80:443"
    - "8080:80"
  links:
    - registry:registry
    - jenkinsmaster:jenkinsmaster
  volumes:
    - ./nginx/:/etc/nginx/conf.d:ro
